

INSERT INTO "public"."drug"("id","generic_name","brand_name","drug_class","schedule")
VALUES
(1,E'Levothyroxine',E'Synthroid',E'Hormone replacement',E'-'),
(2,E'Hydrocodone/APAP',E'Vicodin',E'Analgesic',E'C-II'),
(3,E'Amoxicillin',E'Amoxil',E'Antibiotic',E'-'),
(4,E'Lisinopril',E'Prinivil',E'Antihypertensive',E'-'),
(5,E'Esomeprazole',E'Nexium',E'Antacid (PPI)',E'-'),
(6,E'Atorvastatin',E'Lipitor',E'Cholesterol lowering',E'-'),
(7,E'Simvastatin',E'Zocor',E'Cholesterol lowering',E'-'),
(8,E'Clopidogrel',E'Plavix',E'Anticoagulant',E'-'),
(9,E'Montelukast',E'Singulair',E'Anti-asthmatic',E'-'),
(10,E'Rosuvastatin',E'Crestor',E'Cholesterol lowering',E'-'),
(11,E'Metoprolol',E'Lopressor',E'Antihypertensive',E'-'),
(12,E'Escitalopram',E'Lexapro',E'Antidepressant',E'-'),
(13,E'Azithromycin',E'Zithromax',E'Antibiotic',E'-'),
(14,E'Albuterol',E'ProAir HFA',E'Anti-asthmatic',E'-'),
(15,E'Hydrochlorothiazide',E'HCTZ',E'Diuretic',E'-'),
(16,E'Metformin',E'Glucophage',E'Antidiabetic',E'-'),
(17,E'Sertraline',E'Zoloft',E'Antidepressant',E'-'),
(18,E'Ibuprofen',E'Advil',E'Analgesic (NSAID)',E'-'),
(19,E'Zolpidem',E'Ambien',E'Sleep aid',E'C-IV'),
(20,E'Furosemide',E'Lasix',E'Diuretic',E'-'),
(21,E'Omeprazole',E'Prilosec',E'Antacid (PPI)',E'-'),
(22,E'Trazodone',E'Desyrel',E'Antidepressant',E'-'),
(23,E'Valsartan',E'Diovan',E'Antihypertensive',E'-'),
(24,E'Tramadol',E'Ultram',E'Analgesic',E'C-IV'),
(25,E'Duloxetine',E'Cymbalta',E'Antidepressant',E'-'),
(26,E'Warfarin',E'Coumadin',E'Anticoagulant',E'-'),
(27,E'Amlodipine',E'Norvasc',E'Antihypertensive',E'-'),
(28,E'Oxycodone/APAP',E'Percocet',E'Analgesic',E'C-II'),
(29,E'Quetiapine',E'Seroquel',E'Antipsychotic',E'-'),
(30,E'Promethazine',E'Phenergan',E'Antihistamine',E'-'),
(31,E'Fluticasone',E'Flonase',E'Antihistamine',E'-'),
(32,E'Alprazolam',E'Xanax',E'Antianxiety',E'C-IV'),
(33,E'Clonazepam',E'Klonopin',E'Antianxiety',E'C-IV'),
(34,E'Benazepril',E'Lotensin',E'Antihypertensive',E'-'),
(35,E'Meloxicam',E'Mobic',E'Analgesic (NSAID)',E'-'),
(36,E'Citalopram',E'Celexa',E'Antidepressant',E'-'),
(37,E'Cephalexin',E'Keflex',E'Antibiotic',E'-'),
(38,E'Tiotropium',E'Spiriva',E'C.O.P.D.',E'-'),
(39,E'Gabapentin',E'Neurontin',E'Anticonvulsant',E'-'),
(40,E'Aripiprazole',E'Abilify',E'Antipsychotic',E'-'),
(41,E'Potassium',E'K-Tab',E'Electrolyte',E'-'),
(42,E'Cyclobenzaprine',E'Flexeril',E'Muscle Relaxer',E'-'),
(43,E'Methylprednisolone',E'Medrol',E'Anti-inflammatory steriod',E'-'),
(44,E'Methylphenidate',E'Concerta',E'ADHD',E'C-II'),
(45,E'Fexofenadine',E'Allegra',E'Antihistamine',E'-'),
(46,E'Carvedilol',E'Coreg',E'Antihypertensive',E'-'),
(47,E'Carisoprodol',E'Soma',E'Muscle Relaxer',E'C-IV'),
(48,E'Digoxin',E'Lanoxin',E'Congestive Heart Failure',E'-'),
(49,E'Memantine',E'Namenda',E'Antidementia',E'-'),
(50,E'Atenolol',E'Tenormin',E'Antihypertensive',E'-'),
(51,E'Diazepam',E'Valium',E'Antianxiety',E'C-IV'),
(52,E'Oxycodone',E'OxyContin',E'Analgesic',E'C-II'),
(53,E'Risedronate',E'Actonel',E'Osteoporosis',E'-'),
(54,E'Folic Acid',E'Folvite',E'Supplement',E'-'),
(55,E'Olmesartan',E'Benicar',E'Antihypertensive',E'-'),
(56,E'Prednisone',E'Deltasone',E'Anti-inflammatory steriod',E'-'),
(57,E'Doxycycline',E'Vibramycin',E'Antibiotic',E'-'),
(58,E'Alendronate',E'Fosamax',E'Osteoporosis',E'-'),
(59,E'Pantoprazole',E'Protonix',E'Antacid (PPI)',E'-'),
(60,E'Tamsulosin',E'Flomax',E'Urinary retention',E'-'),
(61,E'Triamterene/HCTZ',E'Dyazide',E'Diuretic',E'-'),
(62,E'Paroxetine',E'Paxil',E'Antidepressant',E'-'),
(63,E'Buprenorphine / Naloxone',E'Suboxone',E'Opioid Addiction',E'C-III'),
(64,E'Enalapril',E'Vasotec',E'Antihypertensive',E'-'),
(65,E'Lovastatin',E'Mevacor',E'Cholesterol lowering',E'-'),
(66,E'Pioglitazone',E'Actos',E'Antidiabetic',E'-'),
(67,E'Pravastatin',E'Pravachol',E'Cholesterol lowering',E'-'),
(68,E'Fluoxetine',E'Prozac',E'Antidepressant',E'-'),
(69,E'Insulin Detemir',E'Levemir',E'Antidiabetic',E'-'),
(70,E'Fluconazole',E'Diflucan',E'Antifungal',E'-'),
(71,E'Levofloxacin',E'Levaquin',E'Antibiotic',E'-'),
(72,E'Rivaroxaban',E'Xarelto',E'Anticoagulant',E'-'),
(73,E'Celecoxib',E'Celebrex',E'Analgesic (NSAID)',E'-'),
(74,E'Codeine / APAP',E'Tylenol #3',E'Analgesic',E'C-III'),
(75,E'Mometasone',E'Nasonex',E'Antihistamine',E'-'),
(76,E'Ciprofloxacin',E'Cipro',E'Antibiotic',E'-'),
(77,E'Pregabalin',E'Lyrica',E'Anticonvulsant',E'-'),
(78,E'Insulin Aspart',E'Novolog',E'Antidiabetic',E'-'),
(79,E'Venlafaxine',E'Effexor',E'Antidepressant',E'-'),
(80,E'Lorazepam',E'Ativan',E'Antianxiety',E'C-IV'),
(81,E'Ezetimibe',E'Zetia',E'Cholesterol lowering',E'-'),
(82,E'Estrogen',E'Premarin',E'Hormone replacement',E'-'),
(83,E'Allopurinol',E'Zyloprim',E'Antigout',E'-'),
(84,E'Penicillin',E'Pen VK',E'Antibiotic',E'-'),
(85,E'Sitagliptin',E'Januvia',E'Antidiabetic',E'-'),
(86,E'Amitriptyline',E'Elavil',E'Antidepressant',E'-'),
(87,E'Clonidine',E'Catapres',E'Antihypertensive',E'-'),
(88,E'Latanoprost',E'Xalatan',E'Antiglaucoma',E'-'),
(89,E'Lisdexamfetamine',E'Vyvanse',E'ADHD',E'C-II'),
(90,E'Niacin',E'Niaspan',E'Cholesterol lowering',E'-'),
(91,E'Naproxen',E'Aleve',E'Analgesic (NSAID)',E'-'),
(92,E'Dexlansoprazole',E'Dexilant',E'Antacid (PPI)',E'-'),
(93,E'Glyburide',E'Diabeta',E'Antidiabetic',E'-'),
(94,E'Olanzapine',E'Zyprexa',E'Antipsychotic',E'-'),
(95,E'Tolterodine',E'Detrol',E'Incontinence',E'-'),
(96,E'Ranitidine',E'Zantac',E'Antacid (H2)',E'-'),
(97,E'Famotidine',E'Pepcid',E'Antacid (H2)',E'-'),
(98,E'Diltiazem',E'Cardizem',E'Antihypertensive',E'-'),
(99,E'Insulin Glargine',E'Lantus',E'Antidiabetic',E'-'),
(100,E'Thyroid',E'Armour Thyroid',E'Hormone replacement',E'-'),
(101,E'Bupropion',E'Wellbutrin',E'Antidepressant',E'-'),
(102,E'Cetirizine',E'Zyrtec',E'Antihistamine',E'-'),
(103,E'Topiramate',E'Topamax',E'Anticonvulsant',E'-'),
(104,E'Valacyclovir',E'Valtrex',E'Antiviral',E'-'),
(105,E'Eszopiclone',E'Lunesta',E'Sleep Aid',E'C-IV'),
(106,E'Acyclovir',E'Zovirax',E'Antiviral',E'-'),
(107,E'Cefdinir',E'Omnicef',E'Antibiotic',E'-'),
(108,E'Clindamycin',E'Cleocin',E'Antibiotic',E'-'),
(109,E'Colchicine',E'Colcrys',E'Antigout',E'-'),
(110,E'Gemfibrozil',E'Lopid',E'Cholesterol lowering',E'-'),
(111,E'Guiafenesin',E'Robitussin',E'Expectorant',E'-'),
(112,E'Glipizide',E'Glucotrol',E'Antidiabetic',E'-'),
(113,E'Irbesartan',E'Avapro',E'Antihypertensive',E'-'),
(114,E'Metoclopramide',E'Reglan',E'Antispasmodic',E'-'),
(115,E'Losartan',E'Cozaar',E'Antihypertensive',E'-'),
(116,E'Meclizine',E'Dramamine',E'Antiemetic',E'-'),
(117,E'Metronidazole',E'Flagyl',E'Antibiotic',E'-'),
(118,E'Vitamin D',E'Caltrate',E'Supplement',E'-'),
(119,E'Testosterone',E'AndroGel',E'Hormone replacement',E'C-III'),
(120,E'Ropinirole',E'Requip',E'Anti-Parkinson\'s',E'-'),
(121,E'Risperidone',E'Risperdal',E'Antipsychotic',E'-'),
(122,E'Olopatadine',E'Patanol',E'Antihistamine',E'-'),
(123,E'Moxifloxacin',E'Avelox',E'Antibiotic',E'-'),
(124,E'Dexmethylphenidate',E'Focalin',E'ADHD',E'C-II'),
(125,E'Enoxaparin',E'Lovenox',E'Anticoagulant',E'-'),
(126,E'Fentanyl',E'Duragesic',E'Analgesic',E'C-II'),
(127,E'Dicyclomine',E'Bentyl',E'Antispasmodic',E'-'),
(128,E'Bisoprolol',E'Zebeta',E'Antihypertensive',E'-'),
(129,E'Atomoxetine',E'Strattera',E'ADHD',E'-'),
(130,E'Ramipril',E'Altace',E'Antihypertensive',E'-'),
(131,E'Temazepam',E'Restoril',E'Sleep Aid',E'C-IV'),
(132,E'Phentermine',E'Adipex P',E'Appetite suppressant',E'C-IV'),
(133,E'Quinapril',E'Accupril',E'Antihypertensive',E'-'),
(134,E'Sildenafil',E'Viagra',E'Erectile dysfunction',E'-'),
(135,E'Ondansetron',E'Zofran',E'Antiemetic',E'-'),
(136,E'Oseltamivir',E'Tamiflu',E'Antiviral',E'-'),
(137,E'Methotrexate',E'Rheumatrex',E'Antirheumatic',E'-'),
(138,E'Dabigatran',E'Pradaxa',E'Anticoagulant',E'-'),
(139,E'Budesonide',E'Uceris',E'Anti-inflammatory',E'-'),
(140,E'Doxazosin',E'Cardura',E'Urinary retention / Antihypertensive',E'-'),
(141,E'Desvenlafaxine',E'Pristiq',E'Antidepressant',E'-'),
(142,E'Insulin Lispro',E'Humalog',E'Antidiabetic',E'-'),
(143,E'Clarithromycin',E'Biaxin',E'Antibiotic',E'-'),
(144,E'Buspirone',E'Buspar',E'Antianxiety',E'-'),
(145,E'Finasteride',E'Proscar',E'Antihypertensive',E'-'),
(146,E'Ketoconazole',E'Nizoral',E'Antifungal',E'-'),
(147,E'Solifenacin',E'VESIcare',E'Bladder relaxant',E'-'),
(148,E'Methadone',E'Dolophine',E'Opioid addiction',E'C-II'),
(149,E'Minocycline',E'Minocin',E'Antibiotic',E'-'),
(150,E'Phenazopyridine',E'Pyridium',E'Analgesic (urinary)',E'-'),
(151,E'Spironolactone',E'Aldactone',E'Diuretic',E'-'),
(152,E'Vardenafil',E'Levitra',E'Erectile dysfunction',E'-'),
(153,E'Clobetasol',E'Clovate',E'Anti-inflammatory steriod',E'-'),
(154,E'Benzonatate',E'Tessalon',E'Antitussive (cough suppressant)',E'-'),
(155,E'Divalproex',E'Depakote',E'Anticonvulsant',E'-'),
(156,E'Dutasteride',E'Avodart',E'Antihypertensive',E'-'),
(157,E'Febuxostat',E'Uloric',E'Antigout',E'-'),
(158,E'Lamotrigine',E'Lamictal',E'Antiepileptic',E'-'),
(159,E'Nortriptyline',E'Pamelor',E'Antidepressant',E'-'),
(160,E'Roflumilast',E'Daliresp',E'C.O.P.D.',E'-'),
(161,E'Rabeprazole',E'Aciphex',E'Antacid (PPI)',E'-'),
(162,E'Etanercept',E'Enbrel',E'Anti-arthritic',E'-'),
(163,E'Nebivolol',E'Bystolic',E'Antihypertensive',E'-'),
(164,E'Nabumetone',E'Relafen',E'Analgesic (NSAID)',E'-'),
(165,E'Nifedipine',E'Procardia',E'Antihypertensive',E'-'),
(166,E'Nitrofurantoin',E'Macrobid',E'Antibiotic',E'-'),
(167,E'Nitroglycerine',E'NitroStat SL',E'Anti-angina',E'-'),
(168,E'Oxybutynin',E'Ditropan',E'Incontinence',E'-'),
(169,E'Tadalifil',E'Cialis',E'Erectile dysfunction',E'-'),
(170,E'Triamcinolone',E'Kenalog',E'Anti-inflammatory steriod',E'-'),
(171,E'Rivastigmine',E'Exelon',E'Antidementia',E'-'),
(172,E'Lansoprazole',E'Prevacid',E'Antacid (PPI)',E'-'),
(173,E'Cefuroxime',E'Ceftin',E'Antibiotic',E'-'),
(174,E'Methocarbamol',E'Robaxin',E'Muscle Relaxer',E'-'),
(175,E'Travoprost',E'Travatan',E'Antiglaucoma',E'-'),
(176,E'Lurasidone',E'Latuda',E'Antipsychotic',E'-'),
(177,E'Terazosin',E'Hytrin',E'Antihypertensive',E'-'),
(178,E'Sumatriptan',E'Imitrex',E'Antimigraine',E'-'),
(179,E'Raloxifene',E'Evista',E'Osteoporosis',E'-'),
(180,E'Mirtazepine',E'Remeron',E'Antidepressant',E'-'),
(181,E'Adalimumab',E'Humira',E'Immunosuppressant',E'-'),
(182,E'Benztropine',E'Cogentin',E'Anti-Parkinson\'s',E'-'),
(183,E'Baclofen',E'Gablofen',NULL,E'-'),
(184,E'Hydralazine',E'Apresoline',E'Antihypertensive',E'-'),
(185,E'Mupirocin',E'Bactroban',E'Antibiotic',E'-'),
(186,E'Propranolol',E'Inderal',E'Antihypertensive',E'-'),
(187,E'Varenicline',E'Chantix',E'Anti-smoking',E'-'),
(188,E'Verapamil',E'Verelan',E'Antihypertensive',E'-'),
(189,E'Clotrimazole',E'Lotrimin',E'Antifungal',E'-'),
(190,E'Phenytoin',E'Dilantin',E'Anticonvulsant',E'-'),
(191,E'Pramipexole',E'Mirapex',E'Anti-Parkinson\'s',E'-'),
(192,E'Liraglutide',E'Victoza',E'Antidiabetic',E'-'),
(193,E'Ticagrelor',E'Brilinta',E'Anticoagulant',E'-'),
(194,E'Diclofenac',E'Voltaren',E'Analgesic (NSAID)',E'-'),
(195,E'Saxagliptin',E'Onglyza',E'Antidiabetic',E'-'),
(196,E'Lomitapide',E'Juxtapid',E'Cholesterol lowering',E'-'),
(197,E'Tizanidine',E'Zanaflex',E'Muscle Relaxer',E'-'),
(198,E'Amphetamine / Dextroamphetamine',E'Adderall',E'ADHD',E'C-II'),
(199,E'Zoster Vaccine',E'Zostavax',E'Shingles Vaccine',E'-'),
(200,E'Ezetimibe Simvastatin',E'Vytorin',E'Cholesterol lowering',E'-');

INSERT INTO "public"."customer"("id","name","dob")
VALUES
(1,E'Erik Bylund',E'1990-11-20');